### ISSUE TITLE
Task completion flow

### ISSUE THREAD

**Issue by njsfield** [smarthutza/flexbox-workshop#1]
This is a great workshop, the challenges are fun to solve and engage the learner to apply key flexbox concepts.

I think a suggested flow of completion could really help, as the learner may struggle to find a suitable starting point.

Perhaps in the instructions in the css file you could advise;
1. First, apply rules to the body tag to set the elements in a row.
2. Solve each dice seperately and then move onto the next.

This could prevent learners from feeling overwhelmed by the challenges, and ensure they're building on techniques applied on previous dice components.

**Comment by smarthutza** [comment]
@njsfield Very good point. I have added the instructions you suggested. Indeed, much clearer now. Thank you for your feedback!
