### ISSUE TITLE
Introducing CSS Grid too

### ISSUE THREAD

**Issue by oliverjam** [smarthutza/flexbox-workshop#4]
I'm a massive fan of CSS grid, but I'm not sure a flexbox workshop is the best place to introduce it. I guess it's okay as an extra resource, but I don't know how relevant it is — grid is a totally separate layout system (that's much newer and less well supported)

**Comment by smarthutza** [comment]
The reason why I've put CSS Grid in 'Further Readings' is because I wanted the students to be aware of its existence as well. But perhaps you're right and it's a bit too much and it gets confusing. I've now removed that resource. Thanks.
